// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ikmJWfGd-8pNFmf2mkf1iyCYk_uSBqU',
    appId: '1:756527807127:web:b02ea942bc21ef9c0c07d2',
    messagingSenderId: '756527807127',
    projectId: 'book-recommendation-d4c4b',
    authDomain: 'book-recommendation-d4c4b.firebaseapp.com',
    storageBucket: 'book-recommendation-d4c4b.firebasestorage.app',
    measurementId: 'G-BKVS0CL0Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs72zdBJLOWbVPmZbdN7vbsSycQ6Xd0GQ',
    appId: '1:756527807127:android:0fbebc428240b90f0c07d2',
    messagingSenderId: '756527807127',
    projectId: 'book-recommendation-d4c4b',
    storageBucket: 'book-recommendation-d4c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrStAFYOgjtgjb-PXaLsILhzF--uFQFrY',
    appId: '1:756527807127:ios:3ab0c753f714b7c30c07d2',
    messagingSenderId: '756527807127',
    projectId: 'book-recommendation-d4c4b',
    storageBucket: 'book-recommendation-d4c4b.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrStAFYOgjtgjb-PXaLsILhzF--uFQFrY',
    appId: '1:756527807127:ios:3ab0c753f714b7c30c07d2',
    messagingSenderId: '756527807127',
    projectId: 'book-recommendation-d4c4b',
    storageBucket: 'book-recommendation-d4c4b.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ikmJWfGd-8pNFmf2mkf1iyCYk_uSBqU',
    appId: '1:756527807127:web:e374d25f258ab22d0c07d2',
    messagingSenderId: '756527807127',
    projectId: 'book-recommendation-d4c4b',
    authDomain: 'book-recommendation-d4c4b.firebaseapp.com',
    storageBucket: 'book-recommendation-d4c4b.firebasestorage.app',
    measurementId: 'G-ZRS6WRG6XC',
  );

}