// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANcyL-r1i2ED0WV4RfGule3OzvLlIAfaw',
    appId: '1:873549081857:web:d616b611d6a2bdec96bf00',
    messagingSenderId: '873549081857',
    projectId: 'book-recomend',
    authDomain: 'book-recomend.firebaseapp.com',
    storageBucket: 'book-recomend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTSQ9PYjlMom0JIDRno8_r_Rk7prHlss',
    appId: '1:873549081857:android:783325a3e793c2c396bf00',
    messagingSenderId: '873549081857',
    projectId: 'book-recomend',
    storageBucket: 'book-recomend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3EAX22FdVBoaUOjiovBSmNeZoOspJLQY',
    appId: '1:873549081857:ios:62bbb3e5efddb70796bf00',
    messagingSenderId: '873549081857',
    projectId: 'book-recomend',
    storageBucket: 'book-recomend.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3EAX22FdVBoaUOjiovBSmNeZoOspJLQY',
    appId: '1:873549081857:ios:62bbb3e5efddb70796bf00',
    messagingSenderId: '873549081857',
    projectId: 'book-recomend',
    storageBucket: 'book-recomend.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANcyL-r1i2ED0WV4RfGule3OzvLlIAfaw',
    appId: '1:873549081857:web:4aea21567f7bb32b96bf00',
    messagingSenderId: '873549081857',
    projectId: 'book-recomend',
    authDomain: 'book-recomend.firebaseapp.com',
    storageBucket: 'book-recomend.firebasestorage.app',
  );
}
